global using System;
global using System.IO;
global using System.Text;
global using System.Threading.Tasks;
global using FluentAssertions;
global using Sirh3e.Rust.Option;
global using Sirh3e.Rust.Panic;
global using Sirh3e.Rust.Result;
global using Xunit;
global using static Sirh3e.Rust.Option.Extension;
global using static Sirh3e.Rust.Result.Extension;