name: .NET Format

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
     
    - name: dotnet tool install dotnet-format
      run: dotnet tool install -g dotnet-format
    
    - name: dotnet format
      run: dotnet format Rust.sln --check -v diag