name: .NET Core Test
on:
  push:
    paths:
    - 'src/**'
    - 'test/**'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        dotnet-version: [ '2.1.x', '2.2.x', '3.0.x', '3.1.x', '5.0.x', '6.0.x' ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --no-restore